export const SUBMIT_FORM = 'SUBMIT_FORM';
export const REGISTRATION_SUBMIT_FORM = 'REGISTRATION_SUBMIT_FORM'
export const AUTHORIZATION_SUBMIT_FORM = 'AUTHORIZATION_SUBMIT_FORM';
export const ERROR_SUBMIT = 'ERROR_SUBMIT';
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const EXIT_FROM_ACCOUNT = 'EXIT_FROM_ACCOUNT';